// Role-Based Access Control Configuration
const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  PRINCIPAL: 'principal',
  DEPUTY_ADMIN: 'deputy_admin',
  DEPUTY_ACADEMIC: 'deputy_academic',
  TEACHER: 'teacher',
  BURSAR: 'bursar',
  LIBRARIAN: 'librarian',
  PARENT: 'parent',
  STUDENT: 'student',
};

const PERMISSIONS = {
  // User Management
  CREATE_USER: 'create:user',
  EDIT_USER: 'edit:user',
  DELETE_USER: 'delete:user',
  VIEW_USER: 'view:user',

  // Student Management
  CREATE_STUDENT: 'create:student',
  EDIT_STUDENT: 'edit:student',
  APPROVE_STUDENT: 'approve:student',
  VIEW_STUDENT: 'view:student',

  // Academics
  CREATE_EXAM: 'create:exam',
  ENTER_MARKS: 'enter:marks',
  APPROVE_MARKS: 'approve:marks',
  VIEW_MARKS: 'view:marks',
  LOCK_EXAM: 'lock:exam',
  VIEW_RESULTS: 'view:results',

  // Finance
  CREATE_FEE_STRUCTURE: 'create:fee_structure',
  RECORD_PAYMENT: 'record:payment',
  VERIFY_PAYMENT: 'verify:payment',
  VIEW_FINANCE: 'view:finance',

  // Attendance
  RECORD_ATTENDANCE: 'record:attendance',
  VIEW_ATTENDANCE: 'view:attendance',

  // Library
  MANAGE_BOOKS: 'manage:books',
  ISSUE_BOOKS: 'issue:books',
  VIEW_LIBRARY: 'view:library',

  // Discipline
  CREATE_DISCIPLINE_CASE: 'create:discipline_case',
  MANAGE_DISCIPLINE: 'manage:discipline',
  VIEW_DISCIPLINE: 'view:discipline',

  // Transfers
  MANAGE_TRANSFERS: 'manage:transfers',

  // Calendar
  MANAGE_CALENDAR: 'manage:calendar',

  // Payroll
  MANAGE_PAYROLL: 'manage:payroll',

  // Reports
  VIEW_REPORTS: 'view:reports',

  // System
  MANAGE_SYSTEM: 'manage:system',
  VIEW_AUDIT_LOG: 'view:audit_log',
};

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.ADMIN]: [
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.EDIT_USER,
    PERMISSIONS.DELETE_USER,
    PERMISSIONS.VIEW_USER,
    PERMISSIONS.CREATE_STUDENT,
    PERMISSIONS.EDIT_STUDENT,
    PERMISSIONS.APPROVE_STUDENT,
    PERMISSIONS.VIEW_STUDENT,
    PERMISSIONS.CREATE_EXAM,
    PERMISSIONS.VIEW_MARKS,
    PERMISSIONS.APPROVE_MARKS,
    PERMISSIONS.LOCK_EXAM,
    PERMISSIONS.VIEW_RESULTS,
    PERMISSIONS.CREATE_FEE_STRUCTURE,
    PERMISSIONS.RECORD_PAYMENT,
    PERMISSIONS.VERIFY_PAYMENT,
    PERMISSIONS.VIEW_FINANCE,
    PERMISSIONS.RECORD_ATTENDANCE,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.MANAGE_BOOKS,
    PERMISSIONS.ISSUE_BOOKS,
    PERMISSIONS.VIEW_LIBRARY,
    PERMISSIONS.MANAGE_DISCIPLINE,
    PERMISSIONS.MANAGE_TRANSFERS,
    PERMISSIONS.MANAGE_CALENDAR,
    PERMISSIONS.MANAGE_PAYROLL,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_SYSTEM,
    PERMISSIONS.VIEW_AUDIT_LOG,
  ],

  [ROLES.PRINCIPAL]: [
    PERMISSIONS.APPROVE_STUDENT,
    PERMISSIONS.APPROVE_MARKS,
    PERMISSIONS.LOCK_EXAM,
    PERMISSIONS.VIEW_STUDENT,
    PERMISSIONS.VIEW_MARKS,
    PERMISSIONS.VIEW_RESULTS,
    PERMISSIONS.VIEW_FINANCE,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_LIBRARY,
    PERMISSIONS.CREATE_DISCIPLINE_CASE,
    PERMISSIONS.MANAGE_DISCIPLINE,
    PERMISSIONS.MANAGE_TRANSFERS,
    PERMISSIONS.MANAGE_CALENDAR,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_AUDIT_LOG,
  ],

  [ROLES.DEPUTY_ACADEMIC]: [
    PERMISSIONS.CREATE_EXAM,
    PERMISSIONS.VIEW_MARKS,
    PERMISSIONS.APPROVE_MARKS,
    PERMISSIONS.LOCK_EXAM,
    PERMISSIONS.VIEW_RESULTS,
    PERMISSIONS.VIEW_STUDENT,
    PERMISSIONS.MANAGE_CALENDAR,
  ],

  [ROLES.DEPUTY_ADMIN]: [
    PERMISSIONS.RECORD_ATTENDANCE,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_STUDENT,
    PERMISSIONS.CREATE_DISCIPLINE_CASE,
    PERMISSIONS.MANAGE_DISCIPLINE,
    PERMISSIONS.MANAGE_TRANSFERS,
  ],

  [ROLES.TEACHER]: [
    PERMISSIONS.ENTER_MARKS,
    PERMISSIONS.RECORD_ATTENDANCE,
    PERMISSIONS.VIEW_STUDENT,
    PERMISSIONS.VIEW_RESULTS,
    PERMISSIONS.VIEW_LIBRARY,
  ],

  [ROLES.BURSAR]: [
    PERMISSIONS.CREATE_FEE_STRUCTURE,
    PERMISSIONS.RECORD_PAYMENT,
    PERMISSIONS.VERIFY_PAYMENT,
    PERMISSIONS.VIEW_FINANCE,
    PERMISSIONS.VIEW_STUDENT,
    PERMISSIONS.MANAGE_PAYROLL,
  ],

  [ROLES.LIBRARIAN]: [
    PERMISSIONS.MANAGE_BOOKS,
    PERMISSIONS.ISSUE_BOOKS,
    PERMISSIONS.VIEW_LIBRARY,
    PERMISSIONS.VIEW_STUDENT,
  ],

  [ROLES.PARENT]: [
    PERMISSIONS.VIEW_STUDENT,
    PERMISSIONS.VIEW_RESULTS,
    PERMISSIONS.VIEW_FINANCE,
    PERMISSIONS.VIEW_ATTENDANCE,
  ],

  [ROLES.STUDENT]: [
    PERMISSIONS.VIEW_RESULTS,
    PERMISSIONS.VIEW_FINANCE,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_LIBRARY,
  ],
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
};
